#!/usr/bin/env python

import os, sys, subprocess

try:
    import asyncio
except ImportError:
    # remove this when implimented https://github.com/rethinkdb/rethinkdb/issues/4139
    sys.stderr.write('This test requires the asyncio module from Python 3.4')
    sys.exit(0)

sys.exit(subprocess.call([os.environ.get('INTERPRETER_PATH', 'python'), os.path.join(os.path.dirname(__file__), 'asyncio_connection.py')]))
